<?php

namespace StockBundle\Repository;

/**
 * AchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchatRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAchat( $sort, $filters = null, $dates = null) {
        $dql = '
                SELECT ach FROM StockBundle:Achat ach JOIN ach.article art
            
             ';
        //$dqlWhere = 'WHERE u.id = :id';
        $dqlWhere = '';
        $dqlFilters = "";
        /*if($filters != null) {
            foreach ($filters as $key => $value) {
                $value = str_replace(['\''], ['\'\''],$value);
                if ($key == 'k.id') {
                    if (trim($value) != "") {
                        $dql .= 'INNER JOIN kr.kpi k ';
                        $dqlFilters .= " AND " . $key . " LIKE '%" . $value . "%'";
                    }
                } else if ($key == "ra.id") {
                    if (trim($value) != "") {
                        $dql .= 'INNER JOIN rr.rapport ra ';
                        $dqlFilters .= " AND " . $key . " LIKE '%" . $value . "%'";}

                } else {
                    $dqlFilters .= " AND " . $key . " LIKE '%" . $value . "%'";
                }
            }
        }*/
        $dql = $dql . " " . $dqlWhere . " " . $dqlFilters;

        /*if ($dates != null) {
            if ($dates['from'] != '') {
                $date = \DateTime::createFromFormat("d/m/Y", $dates['from']);
                $dql .= " AND r.createdAt >= '".$date->format('Y-m-d 00:00:00')."'";
            }
            if ($dates['to'] != '') {
                $date = \DateTime::createFromFormat("d/m/Y", $dates['to']);
                $dql .= " AND r.createdAt <= '".$date->format('Y-m-d 23:59:59')."'";
            }
        }*/

        //$dql .= ' ORDER BY r.'.$sort[0].' '.$sort[1];

        $query = $this->getEntityManager()->createQuery($dql);

        return $query->getResult();
    }
}
